import { z } from "zod";
import { eq } from "drizzle-orm";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { addAuditEvent, findOrganization, findPermissionForGateway, getDb, listOwnerAudit, listOwnerPermissions, listOwnerRecords } from "./db";
import { accessRequests, organizations, permissions, records } from "../drizzle/schema";
import { invokeLLM } from "./_core/llm";
import { storagePut } from "./storage";
import { canAccess } from "../shared/consent";

const recordSuggestionSchema = z.object({ category: z.string(), sensitivity: z.enum(["Low", "Medium", "High", "Critical"]), scope: z.enum(["View only", "View + verify"]), rationale: z.string() });

export const appRouter = router({
  system: systemRouter,
  auth: router({ me: publicProcedure.query(opts => opts.ctx.user), logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }) }),
  records: router({
    list: protectedProcedure.query(({ ctx }) => listOwnerRecords(ctx.user.id)),
    upload: protectedProcedure.input(z.object({ title: z.string().min(1), category: z.string(), sensitivity: z.enum(["Low", "Medium", "High", "Critical"]), fileName: z.string(), mimeType: z.string(), bytesBase64: z.string() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const bytes = Buffer.from(input.bytesBase64, "base64"); const stored = await storagePut(`${ctx.user.id}-records/${Date.now()}-${input.fileName}`, bytes, input.mimeType); const result = await db.insert(records).values({ ownerId: ctx.user.id, title: input.title, category: input.category, sensitivity: input.sensitivity, fileKey: stored.key, fileUrl: stored.url, mimeType: input.mimeType, sizeBytes: bytes.byteLength, verified: 0 }); return { id: Number(result[0].insertId), url: stored.url }; }),
    create: protectedProcedure.input(z.object({ title: z.string().min(1), category: z.string(), sensitivity: z.enum(["Low", "Medium", "High", "Critical"]), fileKey: z.string(), fileUrl: z.string(), mimeType: z.string().optional(), sizeBytes: z.number().optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.insert(records).values({ ...input, ownerId: ctx.user.id, verified: 0 }); return { id: Number(result[0].insertId) }; }),
    suggestions: protectedProcedure.input(z.object({ fileName: z.string(), extractedText: z.string().max(12000).optional() })).mutation(async ({ input }) => { const response = await invokeLLM({ messages: [{ role: "system", content: "You suggest metadata for a private digital record. Return only JSON matching the requested schema. Suggestions are advisory and must never be treated as automatic assignments." }, { role: "user", content: `Filename: ${input.fileName}\nText: ${input.extractedText ?? "No extracted text available."}` }], response_format: { type: "json_schema", json_schema: { name: "record_suggestions", strict: true, schema: { type: "object", properties: { category: { type: "string" }, sensitivity: { type: "string", enum: ["Low", "Medium", "High", "Critical"] }, scope: { type: "string", enum: ["View only", "View + verify"] }, rationale: { type: "string" } }, required: ["category", "sensitivity", "scope", "rationale"], additionalProperties: false } } } }); const content = response.choices?.[0]?.message?.content; const parsed = typeof content === "string" ? JSON.parse(content) : null; return recordSuggestionSchema.parse(parsed); }),
  }),
  permissions: router({
    list: protectedProcedure.query(({ ctx }) => listOwnerPermissions(ctx.user.id)),
    grant: protectedProcedure.input(z.object({ organization: z.string(), recordId: z.number(), purpose: z.string(), scope: z.enum(["View only", "View + verify"]), expiresAt: z.date().optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); let organization = await findOrganization(input.organization); if (!organization) { const result = await db.insert(organizations).values({ name: input.organization, slug: input.organization.toLowerCase().replace(/[^a-z0-9]+/g, "-") }); organization = { id: Number(result[0].insertId), name: input.organization, slug: input.organization.toLowerCase().replace(/[^a-z0-9]+/g, "-"), createdAt: new Date() }; } const result = await db.insert(permissions).values({ ownerId: ctx.user.id, organizationId: organization.id, recordId: input.recordId, purpose: input.purpose, scope: input.scope, status: "ACTIVE", expiresAt: input.expiresAt }); await addAuditEvent({ ownerId: ctx.user.id, permissionId: Number(result[0].insertId), recordId: input.recordId, organizationId: organization.id, eventType: "PERMISSION_GRANTED", message: `Permission granted to ${organization.name}`, decision: "RECORDED" }); return { id: Number(result[0].insertId) }; }),
    revoke: protectedProcedure.input(z.object({ id: z.number() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(permissions).set({ status: "REVOKED", revokedAt: new Date() }).where(eq(permissions.id, input.id)); await addAuditEvent({ ownerId: ctx.user.id, permissionId: input.id, eventType: "PERMISSION_REVOKED", message: "Permission revoked; future gateway access denied", decision: "RECORDED" }); return { success: true }; }),
  }),
  requests: router({
    list: protectedProcedure.query(async ({ ctx }) => { const db = await getDb(); return db ? db.select().from(accessRequests).where(eq(accessRequests.ownerId, ctx.user.id)) : []; }),
    create: publicProcedure.input(z.object({ ownerId: z.number(), organizationId: z.number(), recordId: z.number(), purpose: z.string() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.insert(accessRequests).values({ ...input, status: "PENDING" }); return { id: Number(result[0].insertId) }; }),
    decide: protectedProcedure.input(z.object({ id: z.number(), status: z.enum(["APPROVED", "DENIED"]) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(accessRequests).set({ status: input.status, decidedAt: new Date() }).where(eq(accessRequests.id, input.id)); await addAuditEvent({ ownerId: ctx.user.id, eventType: "ACCESS_REQUEST_DECIDED", message: `Access request ${input.status.toLowerCase()}`, decision: "RECORDED" }); return { success: true }; }),
  }),
  security: router({ audit: protectedProcedure.query(({ ctx }) => listOwnerAudit(ctx.user.id)) }),
  gateway: router({ check: publicProcedure.input(z.object({ organization: z.string(), recordId: z.number() })).query(async ({ input }) => { const organization = await findOrganization(input.organization); if (!organization) return { allowed: false as const, reason: "Organization is not registered." }; const permission = await findPermissionForGateway(organization.id, input.recordId); const allowed = Boolean(permission && canAccess(permission, new Date())); if (permission) await addAuditEvent({ ownerId: permission.ownerId, recordId: input.recordId, permissionId: permission.id, organizationId: organization.id, eventType: "GATEWAY_CHECK", message: allowed ? `Gateway authorized ${organization.name}` : `Gateway denied ${organization.name} after permission ended`, decision: allowed ? "ALLOWED" : "DENIED" }); return { allowed, reason: allowed ? "Active permission verified." : "No active permission matches this request." }; }) }),
});

export type AppRouter = typeof appRouter;
